  CREATE TABLE PO_ORDER (
  idorder INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PONumber VARCHAR(255) NOT NULL,
  hasInvoice VARCHAR(255) NULL,
  exchangeRate FLOAT NULL,
  totalOrderValue FLOAT NULL,
  totalOrderRefrenceValue FLOAT NULL,
  payementTerms VARCHAR(255) NULL,
  contractRefrence VARCHAR(255) NULL,
  reasonForDecline VARCHAR(255) NULL,
  isCapex INTEGER NULL,
  rimmo VARCHAR(255) NULL,
  fimmo VARCHAR(255) NULL,
  companyIdentification VARCHAR(255) NULL,
  procurementContact VARCHAR(255) NULL,
  technicalContact VARCHAR(255) NULL,
  ourRefrences VARCHAR(255) NULL,
  supplierRefrences VARCHAR(255) NULL,
  deliveryInformation VARCHAR(255) NULL,
  deliveryAdress VARCHAR(255) NULL,
  invoiceAdress VARCHAR(255) NULL,
  invoiceSchedule VARCHAR(255) NULL,
  commitments VARCHAR(255) NULL,
  transportIncoterms VARCHAR(255) NULL,
  descriptionOfScopeOfServices VARCHAR(255) NULL,
  recipientOfGoods VARCHAR(255) NULL,
  conpany VARCHAR(255) NULL,
  immo VARCHAR(255) NULL);
  
  CREATE TABLE PO_COUNTRY (
  idcountry INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  countryName VARCHAR(255) NULL,
  countryCode VARCHAR(255) NULL,
  countryRegion VARCHAR(255) NULL);
  
  CREATE TABLE PO_COMPANY (
  idcompany INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  companyCode VARCHAR(255) NULL,
  companyName VARCHAR(255) NULL,
  hasProcurementSystem INTEGER NULL);
  
  CREATE TABLE PO_PURCHASEITEM (
  idpurchaseItem INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  expenseCategory VARCHAR(2555) NULL,
  description VARCHAR(2555) NULL,
  quantity VARCHAR(2555) NULL,
  unitName VARCHAR(2555) NULL,
  unitPrice FLOAT NULL,
  totalvalue float NULL,
  startingDate DATE NULL,
  isCapex VARCHAR(255) NULL,
  orderPONumber VARCHAR(2555) NULL);



CREATE TABLE PO_SUPLIER (
  idsupplier INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  supplierName VARCHAR(255) NULL,
  supplierEmail VARCHAR(255) NULL,
  supplierAdress VARCHAR(255) NULL,
  supplierPhone VARCHAR(255) NULL,
  supplierFax VARCHAR(255) NULL,
  supplierContactName VARCHAR(255) NULL,
  orderPONumber VARCHAR(255) NULL);

  

CREATE TABLE PO_CURRENCY (
  idcurrency INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  currencyCode VARCHAR(255) NULL,
  currencyName VARCHAR(255) NULL,
  isActive INTEGER NULL);


CREATE TABLE PO_FIMMO (
  idFIMMO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FIMMOcode VARCHAR(255) NULL,
  IMMOname VARCHAR(255) NULL);


  
CREATE TABLE PO_RIMMO (
  idRIMMO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code VARCHAR(255) NULL,
  description VARCHAR(255) NULL,
  isActive INTEGER NULL);


CREATE TABLE PO_COSTCENTER (
  idcostcenter INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  costcenterCode VARCHAR(255) NULL,
  costcenterName VARCHAR(255) NULL,
  isActive INTEGER NULL);


CREATE TABLE PO_CATEGORYOFEXPENSES (
  idcategoryofexpenses INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  categoryofexpensesName VARCHAR(255) NULL,
  categoryofexpensesCode VARCHAR(255) NULL);



CREATE TABLE PO_SBOX (
  idsbox INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sBoxCode VARCHAR(255) NULL,
  description VARCHAR(255) NULL,
  platform VARCHAR(255) NULL);




CREATE TABLE PO_IMMO (
  idIMMO INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IMMOCode VARCHAR(255) NULL,
  IMMOName VARCHAR(255) NULL);




CREATE TABLE PO_PRIMARYCOSTCENTER (
  idprimarycostcenter INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  primarycostcenterCode VARCHAR(255) NULL,
  primarycostcenterDescription VARCHAR(255) NULL,
  isActive INTEGER NULL);




CREATE TABLE PO_PRIMARYSBOX (
  idprimarySBox INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  primarySBoxCode VARCHAR(255) NULL,
  primarySBoxName VARCHAR(255) NULL);



CREATE TABLE PO_COMMENTS (
  idcomments INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  commentsText VARCHAR(256) NULL,
  commentsUser VARCHAR(255) NULL,
  commentsDate DATE NULL,
  orderPONumber VARCHAR(255) NULL);
